<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="LAPTOP-CH6E9HR5" name="pytest" skipped="0" tests="3" time="0.050" timestamp="2020-06-19T21:03:58.537627"><testcase classname="test_calc.TestCalc" file="test_calc.py" line="9" name="test_add1" time="0.001"></testcase><testcase classname="test_calc.TestCalc" file="test_calc.py" line="15" name="test_add2" time="0.001"><failure message="assert 0.2 == 0.3">self = &lt;testing.test_calc.TestCalc object at 0x000002CBDE144C48&gt;

    def test_add2(self):
        calc = Calc()
        result = calc.add(0.1, 0.1)
&gt;       assert result == 0.3
E       assert 0.2 == 0.3

test_calc.py:19: AssertionError</failure></testcase><testcase classname="test_calc.TestCalc" file="test_calc.py" line="20" name="test_add3" time="0.000"></testcase></testsuite></testsuites>