{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_alluredemo1.py:10: AssertionError"}, "description": "this test fails", "start": 1592731463117, "stop": 1592731463117, "uuid": "3daf9a08-3bf9-4aed-af9c-eea2f47fc8a5", "historyId": "9e8d23832460ad3c87806390b91ae72c", "testCaseId": "d3ba699b3e70ee73490c0d009b152181", "fullName": "test_alluredemo1#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo1"}, {"name": "host", "value": "LAPTOP-CH6E9HR5"}, {"name": "thread", "value": "21388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo1"}]}